### ISSUE TITLE
All the modules / Sorting filter

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/Kanakalakshmi-Diamonds#3]
Bug Description: Product Category Shorting filter has UI issue.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/ac62f96f-f364-4ff2-830b-6e0bfbe9edff)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-01-24

**Comment by M8Fayaz** [comment]
Pass
