### ISSUE TITLE
Settings / Banner / Title

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/Kanakalakshmi-Diamonds#35]
Bug Description: Title field should not accept empty space.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/a6dbba57-f81d-4b18-99a9-87a7d960583c)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Bug Description: content field is not accepting the empty space, which means showing it in an error message. That's good for the user experience.
Bug Screenshot:

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/c595c77d-3e53-4037-a298-fc742ced531f
