### ISSUE TITLE
login Screen

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/Kanakalakshmi-Diamonds#5]
Bug Description: Need to validate the Email Id field.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/5e39aa7c-2394-45e8-82b1-7d686122162c)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-01-2024

**Comment by M8Fayaz** [comment]
Pass
