### ISSUE TITLE
Settings / option list / Add new option

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/Kanakalakshmi-Diamonds#67]
Bug Description: after updating the **option list** the system showing the **ShopFeatures updated successfully** popup. 
need to add space between the shop and Features in the popup.

Bug Screenshot or Screen record: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/f2dfb314-ce18-402a-8c37-9df99daebf51)

**Comment by M8Balaji** [comment]
fixed
